SELECT
	e.ID AS EmpID
	, e.FIRST_NAME + ' ' + e.LAST_NAME AS Name
	, CASE WHEN lh.ACTIVE_TRANS IS NULL THEN 0 ELSE 1 END AS ClockedIn
	, lh.ROWID AS LaborHeadRowId
	, CASE WHEN lh.ACTIVE_TRANS IS NULL THEN '' ELSE  
		CASE WHEN ld.TYPE <> 'I' THEN 
			ld.WORKORDER_BASE_ID + '.' + ld.WORKORDER_LOT_ID + ' Seq ' + CAST(ld.OPERATION_SEQ_NO AS VARCHAR) + ' (' + ld.TYPE + ')'
		ELSE 
			i.DESCRIPTION END
	END AS CurrentActivity
	, ld.TYPE AS LaborType
	, ld.TRANSACTION_ID AS LaborID
	, ld.CLOCK_IN AS CurrentActivityClockIn
	, op.CALC_END_QTY - op.COMPLETED_QTY AS PendingQty
	, '' AS SupervisorEmail
	, e.EMAIL_ADDR AS EmployeeEmail
	, e.SHIFT_ID AS Shift
	, e.DEPARTMENT_ID AS Department
FROM
	EMPLOYEE e with(nolock)

	LEFT OUTER JOIN BEZLIO_LABOR_HEAD lh with(nolock) ON
	lh.EMPLOYEE_ID = e.ID
	AND lh.ACTIVE_TRANS = 1
	
	LEFT OUTER JOIN LABOR_TICKET ld with(nolock) ON
	ld.EMPLOYEE_ID = lh.EMPLOYEE_ID
	AND ld.DESCRIPTION = lh.ROWID
	AND ld.CLOCK_OUT IS NULL

	LEFT OUTER JOIN INDIRECT i with(nolock) ON
	i.INDIRECT_CODE = ld.INDIRECT_CODE

	LEFT OUTER JOIN OPERATION op with(nolock) ON
	op.WORKORDER_BASE_ID = ld.WORKORDER_BASE_ID
	AND op.WORKORDER_LOT_ID = ld.WORKORDER_LOT_ID
	AND op.WORKORDER_SPLIT_ID = ld.WORKORDER_SPLIT_ID
	AND op.WORKORDER_SUB_ID = ld.WORKORDER_SUB_ID
	AND op.WORKORDER_TYPE = 'W'
	AND op.SEQUENCE_NO = ld.OPERATION_SEQ_NO
--WHERE	
--	e.EMAIL_ADDR = '{EmailAddress}'