GO

/****** Object:  Table [dbo].[BEZLIO_LABOR_HEAD]    Script Date: 7/13/2017 9:51:41 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BEZLIO_LABOR_HEAD](
	[ROWID] [varchar](36) NOT NULL,
	[EMPLOYEE_ID] [nvarchar](15) NOT NULL,
	[CLOCK_IN_STAMP] [datetime] NOT NULL,
	[ACTIVE_TRANS] [bit] NOT NULL,
 CONSTRAINT [PK_BEZLIO_LABOR_HEAD_1] PRIMARY KEY CLUSTERED 
(
	[ROWID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO