SELECT
	ih.INVOICE_DATE + ih.TERMS_NET_DAYS AS DueDate
	, ih.TOTAL_AMOUNT - ih.PAID_AMOUNT AS InvoiceBal
	, CASE WHEN ih.TYPE = 'M' THEN 1 ELSE 0 END AS CreditMemo
FROM
	RECEIVABLE ih with(nolock)
WHERE
	ih.STATUS = 'A'
	AND ih.TOTAL_AMOUNT > ih.PAID_AMOUNT