SELECT
	CAST(op.WORKORDER_BASE_ID AS VARCHAR) + '.' + CAST(op.WORKORDER_LOT_ID AS VARCHAR) + '.' + CAST(op.WORKORDER_SUB_ID AS VARCHAR) + ' Seq ' + CAST(op.SEQUENCE_NO AS VARCHAR) AS JobID
	, op.WORKORDER_BASE_ID AS BaseId
	, op.WORKORDER_LOT_ID AS LotId
	, op.WORKORDER_SPLIT_ID AS SplitId
	, op.WORKORDER_SUB_ID AS SubId
	, op.SEQUENCE_NO AS OprSeq
	, CAST(SUBSTRING(opb.BITS, 1, BITS_LENGTH - 1) AS VARCHAR(8000)) AS JobDesc
	, op.CALC_END_QTY - op.COMPLETED_QTY AS PendingQty
FROM
	OPERATION op with(nolock)

	LEFT OUTER JOIN OPERATION_BINARY opb with(nolock) ON
	opb.WORKORDER_BASE_ID = op.WORKORDER_BASE_ID
	AND opb.WORKORDER_LOT_ID = op.WORKORDER_LOT_ID
	AND opb.WORKORDER_SPLIT_ID = op.WORKORDER_SPLIT_ID
	AND opb.WORKORDER_SUB_ID = op.WORKORDER_SUB_ID
	AND opb.WORKORDER_TYPE = op.WORKORDER_TYPE
	AND opb.SEQUENCE_NO = op.SEQUENCE_NO
WHERE
	op.CALC_END_QTY - op.COMPLETED_QTY > 0
	AND op.WORKORDER_TYPE = 'W'
	AND op.STATUS = 'R'